name: Build SME Documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

env:
  INSTANCE: 'Writerside/sme'
  ARTIFACT: 'webHelpSME2-all.zip'
  DOCKER_VERSION: '233.14938'
  ALGOLIA_ARTIFACT: 'algolia-indexes-SME.zip'
  ALGOLIA_APP_NAME: '5C3F77C61J'
  ALGOLIA_INDEX_NAME: 'dev_unityedu'
  ALGOLIA_KEY: '${{ secrets.ALGOLIA_KEY_SME }}'
  CONFIG_JSON_PRODUCT: 'SME'
  CONFIG_JSON_VERSION: '1.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build docs using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Save artifact with build results
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}
            artifacts/report.json
            artifacts/${{ env.ALGOLIA_ARTIFACT }}
          retention-days: 7
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: artifacts

      - name: Test documentation
        uses: JetBrains/writerside-checker-action@v1
        with:
          instance: ${{ env.INSTANCE }}
  deploy:
    needs: [build, test] # or just needs: test if you want to ensure testing is completed successfully
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact for deployment
        uses: actions/download-artifact@v4
        with:
          name: docs

      - name: Prepare deployment directory
        run: |
          mkdir -p deployment
          chmod 777 deployment

      - name: Unzip artifact for deployment
        run: unzip -O UTF-8 -qq '${{ env.ARTIFACT }}' -d deployment

      - name: Deploy to Remote Server via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: deployment/
          server-dir: /public_html/documentation/sme/ # Adjust this path as necessary for your remote server structure
        
  publish-indexes:
    needs: [build, test, deploy]
    runs-on: ubuntu-latest
    container:
      image: registry.jetbrains.team/p/writerside/builder/algolia-publisher:2.0.32-3
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docs
      - name: Unzip artifact
        run: |
          unzip -O UTF-8 -qq '${{ env.ALGOLIA_ARTIFACT }}' -d algolia-indexes
          env algolia-key='${{env.ALGOLIA_KEY}}' java -jar /opt/builder/help-publication-agent.jar \
          update-index \
          --application-name '${{env.ALGOLIA_APP_NAME}}' \
          --index-name '${{env.ALGOLIA_INDEX_NAME}}' \
          --product '${{env.CONFIG_JSON_PRODUCT}}' \
          --version '${{env.CONFIG_JSON_VERSION}}' \
          --index-directory algolia-indexes/ \
          2>&1 | tee algolia-update-index-log.txt
